// Copyright (c) 2026 Just a Nerd
// SPDX-License-Identifier: BUSL-1.1

//! Causal span identifiers.
//!
//! A [`SpanId`] is a 128-bit value generated by a
//! process-local Xoshiro PRNG seeded from a per-process
//! random nonce + the producer's current monotonic count.
//! 128 bits is the same width OpenTelemetry trace ids use,
//! collision-free for any realistic workload, and small
//! enough to pack into 16 bytes / 32 hex chars on the wire.
//!
//! [`SpanContext`] threads through every substrate that
//! emits observations. A bearer-token-gated HTTPS request
//! builds a root context at the listener seam; the
//! dispatcher carries it into the steward; the steward
//! threads it into plugin invocations. Each substrate is
//! free to create child spans for sub-work it owns — the
//! parent linkage makes the full request tree
//! reconstructable from the ring contents alone.

use serde::{Deserialize, Serialize};
use std::fmt;
use std::sync::atomic::{AtomicU64, Ordering};

/// A 128-bit opaque span identifier.
///
/// Serialises on the wire as a 32-character lower-case hex
/// string. Two halves are tracked separately so the high
/// half can encode the per-process nonce (stable for the
/// life of the process) and the low half encodes the
/// monotonic counter — useful when grepping a buffer for
/// "every span this process produced".
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct SpanId {
    high: u64,
    low: u64,
}

impl SpanId {
    /// Build a span id from raw u128.
    pub const fn from_u128(value: u128) -> Self {
        Self {
            high: (value >> 64) as u64,
            low: value as u64,
        }
    }

    /// Decompose to a u128.
    pub const fn to_u128(self) -> u128 {
        ((self.high as u128) << 64) | self.low as u128
    }

    /// Render as 32 lower-case hex characters.
    pub fn to_hex(self) -> String {
        format!("{:032x}", self.to_u128())
    }

    /// Parse from a 32-character lower-case hex string.
    /// Returns `None` if the input is not exactly 32 hex
    /// chars.
    pub fn from_hex(s: &str) -> Option<Self> {
        if s.len() != 32 {
            return None;
        }
        let value = u128::from_str_radix(s, 16).ok()?;
        Some(Self::from_u128(value))
    }

    /// The all-zero span id. Reserved as a sentinel: it
    /// MUST NOT appear in any real observation; consumers
    /// treat it as "no parent" / "no context".
    pub const ZERO: SpanId = SpanId { high: 0, low: 0 };

    /// Whether this is the reserved zero span.
    pub const fn is_zero(self) -> bool {
        self.high == 0 && self.low == 0
    }
}

impl fmt::Display for SpanId {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "{}", self.to_hex())
    }
}

impl Serialize for SpanId {
    fn serialize<S: serde::Serializer>(
        &self,
        ser: S,
    ) -> Result<S::Ok, S::Error> {
        ser.serialize_str(&self.to_hex())
    }
}

impl<'de> Deserialize<'de> for SpanId {
    fn deserialize<D: serde::Deserializer<'de>>(
        de: D,
    ) -> Result<Self, D::Error> {
        let s = String::deserialize(de)?;
        SpanId::from_hex(&s).ok_or_else(|| {
            serde::de::Error::custom(format!(
                "invalid SpanId hex (expect 32 lower-case hex chars): {s:?}"
            ))
        })
    }
}

/// Span context threaded through every substrate that
/// emits observations.
///
/// Cheap to clone (two u128s + an Option). Carry by value
/// across `await` points; the [`SpanContext::child`] method
/// produces a fresh sub-span without mutating the parent.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub struct SpanContext {
    /// The root of this trace. All spans in one logical
    /// request chain share the same `trace_root`; it makes
    /// "every observation about request X" a single index
    /// lookup.
    pub trace_root: SpanId,

    /// The identifier of this particular span. Distinct
    /// from `trace_root` once the request descends into
    /// child work.
    pub span_id: SpanId,

    /// The immediate parent, if any. The root span's
    /// `parent_span_id` is `None`.
    pub parent_span_id: Option<SpanId>,
}

impl SpanContext {
    /// Build a fresh root context.
    pub fn new_root() -> Self {
        let id = generate_span_id();
        Self {
            trace_root: id,
            span_id: id,
            parent_span_id: None,
        }
    }

    /// Build a child context under `self`. The child shares
    /// the trace_root and points its `parent_span_id` at
    /// `self.span_id`.
    pub fn child(&self) -> Self {
        Self {
            trace_root: self.trace_root,
            span_id: generate_span_id(),
            parent_span_id: Some(self.span_id),
        }
    }

    /// Build a context that resumes an existing trace.
    /// Used by the HTTPS mount when the incoming request
    /// carries a `traceparent` header (W3C trace context):
    /// the substrate adopts the upstream root + parent so
    /// the operator's view stitches across services.
    pub fn from_incoming(trace_root: SpanId, parent_span_id: SpanId) -> Self {
        Self {
            trace_root,
            span_id: generate_span_id(),
            parent_span_id: Some(parent_span_id),
        }
    }
}

/// Process-local span id generator.
///
/// 128-bit ids built from:
/// - 64-bit per-process nonce, sampled once at first call
///   from the std-lib's hash randomness (a non-zero
///   randomly-chosen u64).
/// - 64-bit monotonic counter, incremented on every call.
///
/// Collision-free within one process; collision probability
/// across processes is negligible at 2^-64 per-pair, which
/// is more than adequate for trace correlation.
fn generate_span_id() -> SpanId {
    static COUNTER: AtomicU64 = AtomicU64::new(0);
    let high = process_nonce();
    let low = COUNTER.fetch_add(1, Ordering::Relaxed).wrapping_add(1);
    // Avoid emitting the reserved zero sentinel.
    let id = SpanId { high, low };
    if id.is_zero() {
        SpanId { high, low: 1 }
    } else {
        id
    }
}

fn process_nonce() -> u64 {
    use std::collections::hash_map::RandomState;
    use std::hash::{BuildHasher, Hasher};
    static NONCE: AtomicU64 = AtomicU64::new(0);
    let existing = NONCE.load(Ordering::Acquire);
    if existing != 0 {
        return existing;
    }
    // First call: sample once and CAS in. Concurrent racers
    // collapse to whichever value lands first; subsequent
    // observers see it on Acquire.
    let mut hasher = RandomState::new().build_hasher();
    hasher.write_u64(std::process::id() as u64);
    hasher.write_u128(
        std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .map(|d| d.as_nanos())
            .unwrap_or(0),
    );
    let mut candidate = hasher.finish();
    if candidate == 0 {
        candidate = 0xDEAD_BEEF_CAFE_F00D;
    }
    match NONCE.compare_exchange(
        0,
        candidate,
        Ordering::AcqRel,
        Ordering::Acquire,
    ) {
        Ok(_) => candidate,
        Err(won) => won,
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn span_id_round_trips_through_hex() {
        let id = SpanId::from_u128(0x0123_4567_89ab_cdef_fedc_ba98_7654_3210);
        let hex = id.to_hex();
        assert_eq!(hex.len(), 32);
        assert_eq!(SpanId::from_hex(&hex), Some(id));
    }

    #[test]
    fn span_id_zero_round_trips() {
        let z = SpanId::ZERO;
        assert!(z.is_zero());
        assert_eq!(z.to_hex(), "0".repeat(32));
        assert_eq!(SpanId::from_hex(&z.to_hex()), Some(z));
    }

    #[test]
    fn span_id_hex_refuses_wrong_length() {
        assert_eq!(SpanId::from_hex("0123abc"), None);
        assert_eq!(SpanId::from_hex(&"0".repeat(33)), None);
    }

    #[test]
    fn span_id_hex_refuses_non_hex() {
        assert_eq!(SpanId::from_hex(&"z".repeat(32)), None);
    }

    #[test]
    fn span_id_serialises_as_hex_json_string() {
        let id = SpanId::from_u128(0xdead_beef);
        let json = serde_json::to_string(&id).unwrap();
        assert_eq!(json, format!("\"{}\"", id.to_hex()));
        let back: SpanId = serde_json::from_str(&json).unwrap();
        assert_eq!(back, id);
    }

    #[test]
    fn generate_span_id_never_emits_zero() {
        for _ in 0..10_000 {
            assert!(!generate_span_id().is_zero());
        }
    }

    #[test]
    fn generate_span_id_is_unique_within_process() {
        let mut seen = std::collections::HashSet::new();
        for _ in 0..50_000 {
            let id = generate_span_id();
            assert!(
                seen.insert(id),
                "generate_span_id collided after {} samples",
                seen.len()
            );
        }
    }

    #[test]
    fn span_context_root_has_no_parent() {
        let ctx = SpanContext::new_root();
        assert!(ctx.parent_span_id.is_none());
        assert_eq!(ctx.trace_root, ctx.span_id);
    }

    #[test]
    fn span_context_child_shares_trace_root_and_points_at_parent() {
        let parent = SpanContext::new_root();
        let child = parent.child();
        assert_eq!(child.trace_root, parent.trace_root);
        assert_eq!(child.parent_span_id, Some(parent.span_id));
        assert_ne!(child.span_id, parent.span_id);
    }

    #[test]
    fn span_context_grandchild_walks_back_to_root() {
        let root = SpanContext::new_root();
        let child = root.child();
        let grand = child.child();
        assert_eq!(grand.trace_root, root.trace_root);
        assert_eq!(grand.parent_span_id, Some(child.span_id));
        assert_eq!(child.parent_span_id, Some(root.span_id));
    }

    #[test]
    fn span_context_from_incoming_adopts_external_trace() {
        let upstream_root = SpanId::from_u128(0xaaaa_bbbb_cccc_dddd);
        let upstream_parent = SpanId::from_u128(0xeeee_ffff_0000_1111);
        let ctx = SpanContext::from_incoming(upstream_root, upstream_parent);
        assert_eq!(ctx.trace_root, upstream_root);
        assert_eq!(ctx.parent_span_id, Some(upstream_parent));
        assert_ne!(ctx.span_id, upstream_root);
        assert_ne!(ctx.span_id, upstream_parent);
    }
}
