// Copyright (c) 2026 Just a Nerd
// SPDX-License-Identifier: BUSL-1.1

//! Python SDK emitter.

use crate::config::PythonConfig;
use crate::rendered::{RenderedFile, RenderedSdk};
use evo_projection_core::{CapabilityRequirement, WireOp};
use evo_sdk_genkit::{
    group_schema, to_pascal_case, IndentWriter, SdkOp, SdkOpGroup,
};

/// Python uses `#` line comments. The generated-code header
/// for Python is the marker phrase formatted as a Python
/// comment block. The CI pre-commit gate matches on the
/// marker substring across every dialect.
const PYTHON_HEADER: &str = "# generated by evo-projection-core; do not edit\n\
                             # hand-edits will be overwritten on next regeneration\n";

/// Render the Python SDK.
pub fn render_sdk(schema: &[WireOp], config: &PythonConfig) -> RenderedSdk {
    let groups = group_schema(schema);
    let mut files: Vec<RenderedFile> = Vec::with_capacity(5 + groups.len());

    files.push(RenderedFile::new("__init__.py", emit_init(&groups, config)));
    files.push(RenderedFile::new("client.py", emit_client(&groups, config)));
    files.push(RenderedFile::new("transport.py", emit_transport()));
    files.push(RenderedFile::new("types.py", emit_types()));
    files.push(RenderedFile::new(
        "modules/__init__.py",
        emit_modules_init(),
    ));

    for g in &groups {
        files.push(RenderedFile::new(
            format!("modules/{}.py", g.name),
            emit_module(g, config),
        ));
    }

    RenderedSdk { files }
}

fn emit_init(groups: &[SdkOpGroup], config: &PythonConfig) -> String {
    let mut out = String::with_capacity(1024);
    out.push_str(PYTHON_HEADER);
    out.push_str(&format!(
        "\"\"\"Top-level package: {}.\n\nGenerated client SDK.\"\"\"\n\n",
        config.package_name
    ));
    out.push_str("from .client import EvoClient\n");
    out.push_str(
        "from .types import CallOpts, SubscribeOpts, WireOpError, WireOpResult\n",
    );
    out.push_str("from .transport import Transport\n");
    for g in groups {
        let class = to_pascal_case(&g.name);
        out.push_str(&format!("from .modules.{} import {}\n", g.name, class));
    }
    out.push_str("\n__all__ = [\n");
    out.push_str("    \"EvoClient\",\n");
    out.push_str("    \"Transport\",\n");
    out.push_str("    \"CallOpts\",\n");
    out.push_str("    \"SubscribeOpts\",\n");
    out.push_str("    \"WireOpError\",\n");
    out.push_str("    \"WireOpResult\",\n");
    for g in groups {
        let class = to_pascal_case(&g.name);
        out.push_str(&format!("    \"{}\",\n", class));
    }
    out.push_str("]\n");
    out
}

fn emit_modules_init() -> String {
    let mut out = String::with_capacity(128);
    out.push_str(PYTHON_HEADER);
    out.push_str("\"\"\"Per-capability-domain modules.\"\"\"\n");
    out
}

fn emit_types() -> String {
    let mut out = String::with_capacity(1024);
    out.push_str(PYTHON_HEADER);
    out.push_str("\"\"\"Shared SDK types.\"\"\"\n\n");
    out.push_str("from __future__ import annotations\n\n");
    out.push_str("from dataclasses import dataclass\n");
    out.push_str("from typing import Any, Optional\n\n\n");

    out.push_str("@dataclass(frozen=True)\n");
    out.push_str("class WireOpError(Exception):\n");
    out.push_str(
        "    \"\"\"Structured error from the framework's error taxonomy.\"\"\"\n\n",
    );
    out.push_str("    code: str\n");
    out.push_str("    message: str\n\n\n");

    out.push_str("@dataclass(frozen=True)\n");
    out.push_str("class WireOpResult:\n");
    out.push_str(
        "    \"\"\"Result of a one-shot wire op dispatch. Exactly one of `value` or `error` is set.\"\"\"\n\n",
    );
    out.push_str("    value: Optional[Any] = None\n");
    out.push_str("    error: Optional[WireOpError] = None\n\n\n");

    out.push_str("@dataclass(frozen=True)\n");
    out.push_str("class CallOpts:\n");
    out.push_str(
        "    \"\"\"Per-call options. Step-up ops require a step-up token bound to the same capability scope.\"\"\"\n\n",
    );
    out.push_str("    step_up_token: Optional[str] = None\n\n\n");

    out.push_str("@dataclass(frozen=True)\n");
    out.push_str("class SubscribeOpts:\n");
    out.push_str(
        "    \"\"\"Per-subscription options. Adds a `since` cursor for `subscribeHappenings`-class replay.\"\"\"\n\n",
    );
    out.push_str("    step_up_token: Optional[str] = None\n");
    out.push_str("    since: Optional[int] = None\n");
    out
}

fn emit_transport() -> String {
    let mut out = String::with_capacity(1024);
    out.push_str(PYTHON_HEADER);
    out.push_str("\"\"\"Transport ABC. Runtime mount implements concrete dispatch + subscribe.\"\"\"\n\n");
    out.push_str("from __future__ import annotations\n\n");
    out.push_str("from abc import ABC, abstractmethod\n");
    out.push_str("from typing import Any, AsyncIterator, Dict\n\n");
    out.push_str(
        "from .types import CallOpts, SubscribeOpts, WireOpResult\n\n\n",
    );

    out.push_str("class Transport(ABC):\n");
    out.push_str(
        "    \"\"\"Dispatch + subscribe surface every module class consumes.\"\"\"\n\n",
    );
    out.push_str("    @abstractmethod\n");
    out.push_str("    async def dispatch(\n");
    out.push_str("        self,\n");
    out.push_str("        op: str,\n");
    out.push_str("        payload: Dict[str, Any],\n");
    out.push_str("        opts: CallOpts,\n");
    out.push_str("    ) -> WireOpResult:\n");
    out.push_str("        ...\n\n");
    out.push_str("    @abstractmethod\n");
    out.push_str("    def subscribe(\n");
    out.push_str("        self,\n");
    out.push_str("        op: str,\n");
    out.push_str("        payload: Dict[str, Any],\n");
    out.push_str("        opts: SubscribeOpts,\n");
    out.push_str("    ) -> AsyncIterator[Any]:\n");
    out.push_str("        ...\n");
    out
}

fn emit_client(groups: &[SdkOpGroup], config: &PythonConfig) -> String {
    let mut out = String::with_capacity(2048);
    out.push_str(PYTHON_HEADER);
    out.push_str("\"\"\"Top-level EvoClient.\"\"\"\n\n");
    out.push_str("from __future__ import annotations\n\n");
    out.push_str("from .transport import Transport\n");
    for g in groups {
        let class = to_pascal_case(&g.name);
        out.push_str(&format!("from .modules.{} import {}\n", g.name, class));
    }
    out.push_str("\n\nclass EvoClient:\n");
    out.push_str(
        "    \"\"\"Top-level client: holds the transport + one attribute per capability domain.\"\"\"\n\n",
    );
    {
        let mut iw = IndentWriter::new(&mut out, &config.indent_unit);
        iw.indent();
        iw.line("def __init__(self, transport: Transport) -> None:");
        iw.indent();
        iw.line("self._transport = transport");
        for g in groups {
            let class = to_pascal_case(&g.name);
            iw.line_fmt(format_args!(
                "self.{}: {} = {}(transport)",
                g.name, class, class
            ));
        }
        iw.dedent();
        iw.dedent();
    }
    out
}

fn emit_module(group: &SdkOpGroup, config: &PythonConfig) -> String {
    let mut out = String::with_capacity(2048);
    out.push_str(PYTHON_HEADER);
    out.push_str(&format!(
        "\"\"\"Operations in the `{}` capability domain.\"\"\"\n\n",
        group.name
    ));
    out.push_str("from __future__ import annotations\n\n");
    out.push_str("from typing import Any, AsyncIterator, Dict, Optional\n\n");
    out.push_str("from ..transport import Transport\n");
    out.push_str(
        "from ..types import CallOpts, SubscribeOpts, WireOpResult\n\n\n",
    );

    let class = to_pascal_case(&group.name);
    out.push_str(&format!("class {}:\n", class));
    out.push_str(&format!(
        "    \"\"\"Operations in the `{}` capability domain.\"\"\"\n\n",
        group.name
    ));

    {
        let mut iw = IndentWriter::new(&mut out, &config.indent_unit);
        iw.indent();
        iw.line("def __init__(self, transport: Transport) -> None:");
        iw.indent();
        iw.line("self._transport = transport");
        iw.dedent();

        for op in &group.ops {
            iw.line("");
            emit_method(&mut iw, op);
        }
        iw.dedent();
    }
    out
}

fn emit_method(iw: &mut IndentWriter<'_>, op: &SdkOp) {
    let scope = match &op.wire_op.capability {
        CapabilityRequirement::None => "anonymous".to_string(),
        CapabilityRequirement::Read { scope } => format!("read({})", scope),
        CapabilityRequirement::Write { scope } => format!("write({})", scope),
        CapabilityRequirement::StepUp { scope } => {
            format!("step-up({})", scope)
        }
    };
    let step_up_note = if op.is_step_up { "yes" } else { "no" };

    if op.is_subscription {
        iw.line_fmt(format_args!("async def {}(", op.method_snake));
        iw.indent();
        iw.line("self,");
        iw.line("payload: Optional[Dict[str, Any]] = None,");
        iw.line("opts: Optional[SubscribeOpts] = None,");
        iw.dedent();
        iw.line(") -> AsyncIterator[Any]:");
        iw.indent();
        iw.line_fmt(format_args!("\"\"\"{}", op.summary()));
        iw.line("");
        iw.line_fmt(format_args!("Capability: {}", scope));
        iw.line_fmt(format_args!("Step-up required: {}", step_up_note));
        iw.line_fmt(format_args!("Wire op id: `{}`", op.wire_op_id_str()));
        iw.line("\"\"\"");
        iw.line("async for event in self._transport.subscribe(");
        iw.indent();
        iw.line_fmt(format_args!("\"{}\",", op.wire_op_id_str()));
        iw.line("payload or {},");
        iw.line("opts or SubscribeOpts(),");
        iw.dedent();
        iw.line("):");
        iw.indent();
        iw.line("yield event");
        iw.dedent();
        iw.dedent();
    } else {
        iw.line_fmt(format_args!("async def {}(", op.method_snake));
        iw.indent();
        iw.line("self,");
        iw.line("payload: Optional[Dict[str, Any]] = None,");
        iw.line("opts: Optional[CallOpts] = None,");
        iw.dedent();
        iw.line(") -> WireOpResult:");
        iw.indent();
        iw.line_fmt(format_args!("\"\"\"{}", op.summary()));
        iw.line("");
        iw.line_fmt(format_args!("Capability: {}", scope));
        iw.line_fmt(format_args!("Step-up required: {}", step_up_note));
        iw.line_fmt(format_args!("Wire op id: `{}`", op.wire_op_id_str()));
        iw.line("\"\"\"");
        iw.line("return await self._transport.dispatch(");
        iw.indent();
        iw.line_fmt(format_args!("\"{}\",", op.wire_op_id_str()));
        iw.line("payload or {},");
        iw.line("opts or CallOpts(),");
        iw.dedent();
        iw.line(")");
        iw.dedent();
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use evo_projection_core::{
        AuditTiming, CapabilityRequirement, WireOp, WireOpId,
    };

    fn op(id: &str, cap: CapabilityRequirement, s: &str) -> WireOp {
        WireOp::new(WireOpId::new(id).unwrap(), cap, AuditTiming::None, s)
    }

    fn fixture() -> Vec<WireOp> {
        vec![
            op(
                "describe_capabilities",
                CapabilityRequirement::None,
                "Discover.",
            ),
            op(
                "list_plugins",
                CapabilityRequirement::read("plugins"),
                "List.",
            ),
            op(
                "set_update_channel",
                CapabilityRequirement::step_up("updates_admin"),
                "Set channel.",
            ),
            op(
                "subscribe_happenings",
                CapabilityRequirement::read("subjects"),
                "Subscribe.",
            ),
        ]
    }

    #[test]
    fn render_emits_scaffolding_files() {
        let sdk = render_sdk(&fixture(), &PythonConfig::default());
        assert!(sdk.find("__init__.py").is_some());
        assert!(sdk.find("client.py").is_some());
        assert!(sdk.find("transport.py").is_some());
        assert!(sdk.find("types.py").is_some());
        assert!(sdk.find("modules/__init__.py").is_some());
    }

    #[test]
    fn render_emits_one_module_per_group() {
        let sdk = render_sdk(&fixture(), &PythonConfig::default());
        assert!(sdk.find("modules/discovery.py").is_some());
        assert!(sdk.find("modules/plugins.py").is_some());
        assert!(sdk.find("modules/subjects.py").is_some());
        assert!(sdk.find("modules/updates_admin.py").is_some());
    }

    #[test]
    fn every_file_carries_generated_header_marker() {
        use evo_projection_core::carries_generated_header;
        let sdk = render_sdk(&fixture(), &PythonConfig::default());
        for f in &sdk.files {
            assert!(
                carries_generated_header(&f.content),
                "{} missing header",
                f.path
            );
        }
    }

    #[test]
    fn init_re_exports_evo_client_and_every_module() {
        let sdk = render_sdk(&fixture(), &PythonConfig::default());
        let init = sdk.find("__init__.py").unwrap();
        assert!(init.content.contains("from .client import EvoClient"));
        assert!(init
            .content
            .contains("from .modules.discovery import Discovery"));
        assert!(init
            .content
            .contains("from .modules.plugins import Plugins"));
        assert!(init
            .content
            .contains("from .modules.updates_admin import UpdatesAdmin"));
    }

    #[test]
    fn client_instantiates_one_module_per_group() {
        let sdk = render_sdk(&fixture(), &PythonConfig::default());
        let client = sdk.find("client.py").unwrap();
        assert!(client.content.contains("class EvoClient:"));
        assert!(client
            .content
            .contains("self.discovery: Discovery = Discovery(transport)"));
        assert!(client
            .content
            .contains("self.plugins: Plugins = Plugins(transport)"));
        assert!(client.content.contains(
            "self.updates_admin: UpdatesAdmin = UpdatesAdmin(transport)"
        ));
    }

    #[test]
    fn one_shot_method_emits_async_def() {
        let sdk = render_sdk(&fixture(), &PythonConfig::default());
        let plugins = sdk.find("modules/plugins.py").unwrap();
        assert!(plugins.content.contains("class Plugins:"));
        assert!(plugins.content.contains("async def list_plugins("));
        assert!(plugins.content.contains(") -> WireOpResult:"));
        assert!(plugins
            .content
            .contains("return await self._transport.dispatch("));
        assert!(plugins.content.contains("\"list_plugins\","));
    }

    #[test]
    fn step_up_method_carries_step_up_note() {
        let sdk = render_sdk(&fixture(), &PythonConfig::default());
        let admin = sdk.find("modules/updates_admin.py").unwrap();
        assert!(admin.content.contains("set_update_channel"));
        assert!(admin.content.contains("Step-up required: yes"));
        assert!(admin.content.contains("Capability: step-up(updates_admin)"));
    }

    #[test]
    fn subscription_method_emits_async_iterator() {
        let sdk = render_sdk(&fixture(), &PythonConfig::default());
        let subjects = sdk.find("modules/subjects.py").unwrap();
        assert!(subjects.content.contains("async def subscribe_happenings("));
        assert!(subjects.content.contains(") -> AsyncIterator[Any]:"));
        assert!(subjects
            .content
            .contains("async for event in self._transport.subscribe("));
        assert!(subjects.content.contains("yield event"));
    }

    #[test]
    fn transport_abc_declares_dispatch_and_subscribe() {
        let sdk = render_sdk(&fixture(), &PythonConfig::default());
        let t = sdk.find("transport.py").unwrap();
        assert!(t.content.contains("class Transport(ABC):"));
        assert!(t.content.contains("@abstractmethod"));
        assert!(t.content.contains("async def dispatch("));
        assert!(t.content.contains(") -> WireOpResult:"));
        assert!(t.content.contains("def subscribe("));
        assert!(t.content.contains(") -> AsyncIterator[Any]:"));
    }

    #[test]
    fn types_file_declares_dataclasses() {
        let sdk = render_sdk(&fixture(), &PythonConfig::default());
        let t = sdk.find("types.py").unwrap();
        assert!(t.content.contains("@dataclass(frozen=True)"));
        assert!(t.content.contains("class WireOpError(Exception):"));
        assert!(t.content.contains("class WireOpResult:"));
        assert!(t.content.contains("class CallOpts:"));
        assert!(t.content.contains("class SubscribeOpts:"));
    }

    #[test]
    fn anonymous_method_carries_anonymous_capability_note() {
        let sdk = render_sdk(&fixture(), &PythonConfig::default());
        let d = sdk.find("modules/discovery.py").unwrap();
        assert!(d.content.contains("Capability: anonymous"));
        assert!(d.content.contains("describe_capabilities"));
    }

    #[test]
    fn empty_schema_emits_scaffolding_only() {
        let sdk = render_sdk(&[], &PythonConfig::default());
        assert!(sdk.find("__init__.py").is_some());
        assert!(sdk.find("modules/__init__.py").is_some());
        assert!(
            sdk.files
                .iter()
                .filter(|f| f.path.starts_with("modules/"))
                .count()
                == 1
        );
    }

    #[test]
    fn render_is_stable_across_repeated_calls() {
        let first = render_sdk(&fixture(), &PythonConfig::default());
        let second = render_sdk(&fixture(), &PythonConfig::default());
        assert_eq!(first, second);
    }
}
