//! Inspect subcommand orchestrator: runs all inspectors against
//! the target, captures findings, runs basic discrepancy rules
//! that compare declared capabilities against detected hardware
//! and configuration, and emits a Markdown inspection report.

use std::fmt::Write as _;
use std::path::Path;
use std::time::Duration;

use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};

use crate::connection;
use crate::discrepancy::{self, Discrepancy};
use crate::error::{HarnessError, Result};
use crate::inspector::{Inspector, InspectorFinding};
use crate::target::TargetDescriptor;

const INSPECTOR_TIMEOUT: Duration = Duration::from_secs(30);

/// Schema version of the inspection report. Bump when the report's
/// structure changes in a way external consumers (e.g. a remote
/// log server, a vendor's diagnostic upload pipeline) would need
/// to detect. Major bump for breaking layout changes; minor for
/// additive fields.
pub const REPORT_SCHEMA_VERSION: &str = "1.0";

#[derive(Debug, Serialize, Deserialize)]
pub struct InspectionReport {
    pub schema_version: String,
    pub target: String,
    pub target_arch: String,
    pub generated_at: DateTime<Utc>,
    pub findings: Vec<InspectorFinding>,
    pub discrepancies: Vec<Discrepancy>,
}

pub async fn run_inspect(
    target: TargetDescriptor,
    output: &Path,
    output_json: Option<&Path>,
) -> Result<InspectionReport> {
    let connection = connection::build(&target)?;

    let mut findings = Vec::new();
    for inspector in Inspector::all() {
        let finding = inspector.probe(&connection, INSPECTOR_TIMEOUT).await?;
        findings.push(finding);
    }

    let discrepancies = discrepancy::evaluate(&target, &findings);

    let report = InspectionReport {
        schema_version: REPORT_SCHEMA_VERSION.to_string(),
        target: target.name.clone(),
        target_arch: target.arch.clone(),
        generated_at: Utc::now(),
        findings,
        discrepancies,
    };

    let body = render_markdown(&report, &target);
    std::fs::write(output, body).map_err(|source| {
        HarnessError::ReportWrite {
            path: output.to_path_buf(),
            source,
        }
    })?;

    if let Some(json_path) = output_json {
        let json = serde_json::to_string_pretty(&report)
            .expect("InspectionReport serialises");
        std::fs::write(json_path, json).map_err(|source| {
            HarnessError::ReportWrite {
                path: json_path.to_path_buf(),
                source,
            }
        })?;
    }

    Ok(report)
}

fn render_markdown(
    report: &InspectionReport,
    target: &TargetDescriptor,
) -> String {
    use crate::discrepancy::Severity;

    let block = report
        .discrepancies
        .iter()
        .filter(|d| d.severity == Severity::Block)
        .count();
    let warn = report
        .discrepancies
        .iter()
        .filter(|d| d.severity == Severity::Warn)
        .count();
    let info = report
        .discrepancies
        .iter()
        .filter(|d| d.severity == Severity::Info)
        .count();
    let total = report.discrepancies.len();

    let mut out = String::new();

    // -------------------------------------------------------------
    // Header — what this report is, generated at, schema version.
    // -------------------------------------------------------------
    let _ = writeln!(out, "# `{}` — Pre-flight Inspection Report", target.name);
    let _ = writeln!(out);
    let _ = writeln!(
        out,
        "Generated by `evo-acceptance inspect` at **{}**.",
        report.generated_at.to_rfc3339()
    );
    let _ = writeln!(out);

    // -------------------------------------------------------------
    // §1 Summary — at-a-glance state for fast triage.
    // -------------------------------------------------------------
    let _ = writeln!(out, "## §1 Summary");
    let _ = writeln!(out);
    let _ = writeln!(out, "| Field | Value |");
    let _ = writeln!(out, "| --- | --- |");
    let _ = writeln!(out, "| Target name | `{}` |", report.target);
    let _ = writeln!(out, "| Target arch | `{}` |", report.target_arch);
    let _ = writeln!(out, "| Inspectors run | {} |", report.findings.len());
    let _ = writeln!(
        out,
        "| Capabilities declared | {} |",
        target.capabilities.len()
    );
    let _ = writeln!(out, "| Discrepancies | **{total}** total — {block} Block / {warn} Warn / {info} Info |");
    let _ = writeln!(out, "| Report schema | `{}` |", report.schema_version);
    let _ = writeln!(
        out,
        "| Generated at | `{}` |",
        report.generated_at.to_rfc3339()
    );
    let _ = writeln!(out);

    // -------------------------------------------------------------
    // §2 Discrepancies — actionable findings first, severity-ordered.
    // -------------------------------------------------------------
    let _ = writeln!(out, "## §2 Discrepancies");
    let _ = writeln!(out);
    if report.discrepancies.is_empty() {
        let _ = writeln!(
            out,
            "✅ No discrepancies detected between declared capabilities and inspected state."
        );
    } else {
        let _ = writeln!(out, "| Severity | Subject | Detail |");
        let _ = writeln!(out, "| --- | --- | --- |");
        // Order: Block, then Warn, then Info, preserving discovery order within each.
        for severity in [Severity::Block, Severity::Warn, Severity::Info] {
            for d in report
                .discrepancies
                .iter()
                .filter(|d| d.severity == severity)
            {
                let detail = d.detail.replace('|', "\\|").replace('\n', " ");
                let badge = match severity {
                    Severity::Block => "🛑 **Block**",
                    Severity::Warn => "⚠ Warn",
                    Severity::Info => "ℹ Info",
                };
                let _ =
                    writeln!(out, "| {badge} | `{}` | {detail} |", d.subject);
            }
        }
    }
    let _ = writeln!(out);

    // -------------------------------------------------------------
    // §3 Declared capabilities — from the target descriptor.
    // -------------------------------------------------------------
    let _ = writeln!(out, "## §3 Declared capabilities");
    let _ = writeln!(out);
    if target.capabilities.is_empty() {
        let _ = writeln!(
            out,
            "_No capabilities declared in the target descriptor._"
        );
    } else {
        let _ = writeln!(out, "Source: `acceptance/targets/{}.toml`. Each capability gates whichever scenarios declare `requires_capability = \"<name>\"`.", target.name);
        let _ = writeln!(out);
        let _ = writeln!(out, "| Capability | Note |");
        let _ = writeln!(out, "| --- | --- |");
        for c in &target.capabilities {
            let note = c
                .note
                .clone()
                .unwrap_or_else(|| "—".to_string())
                .replace('|', "\\|");
            let _ = writeln!(out, "| `{}` | {} |", c.name, note);
        }
    }
    let _ = writeln!(out);

    // -------------------------------------------------------------
    // §4 Inspector findings — raw output, one section per inspector,
    // collapsed under a clear heading + command + exit code.
    // -------------------------------------------------------------
    let _ = writeln!(out, "## §4 Inspector findings");
    let _ = writeln!(out);
    let _ = writeln!(out, "Each inspector is read-only and side-effect-free. Output is captured as observed; no parsing or interpretation beyond the discrepancy rules in §2.");
    let _ = writeln!(out);

    for f in &report.findings {
        let exit_badge = if f.exit_code == 0 { "✅" } else { "⚠" };
        let _ = writeln!(
            out,
            "### `{}`  {} (exit {})",
            f.inspector, exit_badge, f.exit_code
        );
        let _ = writeln!(out);
        let _ = writeln!(out, "<details><summary>Command</summary>");
        let _ = writeln!(out);
        let _ = writeln!(out, "```sh");
        let _ = writeln!(out, "{}", f.command);
        let _ = writeln!(out, "```");
        let _ = writeln!(out);
        let _ = writeln!(out, "</details>");
        let _ = writeln!(out);
        let stdout_trimmed = f.stdout.trim_end();
        if stdout_trimmed.is_empty() {
            let _ = writeln!(out, "_(no stdout)_");
        } else {
            let _ = writeln!(out, "```");
            let _ = writeln!(out, "{stdout_trimmed}");
            let _ = writeln!(out, "```");
        }
        let stderr_trimmed = f.stderr.trim_end();
        if !stderr_trimmed.is_empty() {
            let _ = writeln!(out);
            let _ = writeln!(out, "<details><summary>stderr</summary>");
            let _ = writeln!(out);
            let _ = writeln!(out, "```");
            let _ = writeln!(out, "{stderr_trimmed}");
            let _ = writeln!(out, "```");
            let _ = writeln!(out);
            let _ = writeln!(out, "</details>");
        }
        let _ = writeln!(out);
    }

    // -------------------------------------------------------------
    // §5 Footer — schema, future-direction note.
    // -------------------------------------------------------------
    let _ = writeln!(out, "## §5 Report metadata");
    let _ = writeln!(out);
    let _ = writeln!(
        out,
        "- Report schema version: **{}**",
        report.schema_version
    );
    let _ = writeln!(
        out,
        "- Inspector framework: `evo-acceptance` (workspace crate)"
    );
    let _ = writeln!(out, "- This report's structure is consumable by humans (Markdown) and machines (paired JSON sidecar via `--output-json`).");
    let _ = writeln!(out);
    let _ = writeln!(out, "**Future direction.** This report is also a complete-shape diagnostic bundle: a vendor or distribution can adopt it as the field-diagnostic artefact uploaded by support tooling when an end-user reports a problem. Future versions may add: per-vendor anonymisation of host/IP/serial, tarball bundling of inspect + readiness reports, and a versioned upload contract to a remote diagnostic log server. Until then, the Markdown + JSON sidecar pair travels as-is.");
    let _ = writeln!(out);

    out
}
