//! Readiness report — Markdown output with a fixed ten-section
//! layout. Sections §3-§7 are auto-populated from scenario outcomes.
//! Sections §1, §2, §8, §9, §10 are stubbed for decider authoring.
//!
//! Optional JSON sidecar emits per-scenario pass/fail/skip in
//! machine-readable form.

use std::fmt::Write as _;
use std::path::Path;

use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};

use crate::error::{HarnessError, Result};
use crate::plan::{ScenarioPlan, Tier};
use crate::scenario::{ScenarioOutcome, ScenarioStatus};
use crate::target::TargetDescriptor;

#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "UPPERCASE")]
pub enum Verdict {
    /// Every scenario in the plan executed and passed. Framework
    /// behaviour against this plan is verified.
    Promote,
    /// At least one scenario failed OR at least one scenario skipped.
    /// A skip is not a pass — it means a piece of framework behaviour
    /// was not exercised. Either fix the failing scenario or build
    /// the missing fixture; there is no soft middle.
    Block,
}

#[derive(Debug, Serialize, Deserialize)]
pub struct ReadinessReport {
    pub release: String,
    pub rc: u32,
    pub target: String,
    pub generated_at: DateTime<Utc>,
    pub outcomes: Vec<ScenarioOutcome>,
    pub computed_verdict_hint: Verdict,
}

impl ReadinessReport {
    pub fn new(
        release: String,
        rc: u32,
        target: &TargetDescriptor,
        outcomes: Vec<ScenarioOutcome>,
    ) -> Self {
        let computed_verdict_hint = compute_verdict_hint(&outcomes);
        Self {
            release,
            rc,
            target: target.name.clone(),
            generated_at: Utc::now(),
            outcomes,
            computed_verdict_hint,
        }
    }

    pub fn write_markdown(
        &self,
        plan: &ScenarioPlan,
        target: &TargetDescriptor,
        path: &Path,
    ) -> Result<()> {
        let body = self.render_markdown(plan, target);
        std::fs::write(path, body).map_err(|source| HarnessError::ReportWrite {
            path: path.to_path_buf(),
            source,
        })
    }

    pub fn write_json(&self, path: &Path) -> Result<()> {
        let body = serde_json::to_string_pretty(self)
            .expect("ReadinessReport serialises");
        std::fs::write(path, body).map_err(|source| HarnessError::ReportWrite {
            path: path.to_path_buf(),
            source,
        })
    }

    fn render_markdown(
        &self,
        plan: &ScenarioPlan,
        target: &TargetDescriptor,
    ) -> String {
        let mut out = String::new();

        let pass = self
            .outcomes
            .iter()
            .filter(|o| o.status == ScenarioStatus::Pass)
            .count();
        let fail = self
            .outcomes
            .iter()
            .filter(|o| o.status == ScenarioStatus::Fail)
            .count();
        let skip = self
            .outcomes
            .iter()
            .filter(|o| o.status == ScenarioStatus::Skip)
            .count();
        let total = self.outcomes.len();
        let skip_pct = if total == 0 {
            0.0
        } else {
            (skip as f64) * 100.0 / (total as f64)
        };

        let _ = writeln!(
            out,
            "# {} {}-RC.{} — {} Readiness Report",
            plan.release, self.release, self.rc, target.name
        );
        let _ = writeln!(out);
        let _ = writeln!(
            out,
            "Generated by `evo-acceptance` at {}.",
            self.generated_at.to_rfc3339()
        );
        let _ = writeln!(out);
        let _ = writeln!(out, "Computed verdict hint (auto): **{:?}**. Human-decider verdict goes in §2.", self.computed_verdict_hint);
        let _ = writeln!(out);

        // §1 cut metadata
        let _ = writeln!(out, "## §1 Cut metadata");
        let _ = writeln!(out);
        let _ = writeln!(out, "| Field | Value |");
        let _ = writeln!(out, "| --- | --- |");
        let _ = writeln!(out, "| Release | {} |", self.release);
        let _ = writeln!(out, "| RC | {} |", self.rc);
        let _ = writeln!(out, "| Target name | {} |", target.name);
        let _ = writeln!(out, "| Target arch | {} |", target.arch);
        let _ = writeln!(
            out,
            "| Generated at | {} |",
            self.generated_at.to_rfc3339()
        );
        let _ = writeln!(out, "| Tester | _decider fills this_ |");
        let _ = writeln!(out);

        // §2 executive verdict
        let _ = writeln!(out, "## §2 Executive verdict");
        let _ = writeln!(out);
        let _ = writeln!(
            out,
            "**_PROMOTE / BLOCK — decider chooses (binary; no soft middle)_**"
        );
        let _ = writeln!(out);
        let _ = writeln!(
            out,
            "Auto-computed hint from §3-§7: **{:?}**.",
            self.computed_verdict_hint
        );
        let _ = writeln!(out);
        let _ = writeln!(out, "Justification (decider authors):");
        let _ = writeln!(out);

        // §3 per-scenario coverage
        let _ = writeln!(out, "## §3 Scenario coverage");
        let _ = writeln!(out);
        let _ = writeln!(out, "Total: **{total}**.  Pass: **{pass}**.  Fail: **{fail}**.  Skip: **{skip}** ({skip_pct:.1}%).");
        let _ = writeln!(out);
        if skip > 0 {
            let _ = writeln!(out, "> Any Skip → BLOCK. A skip is unverified surface, not a pass. Build the absent fixtures so the scenarios execute.");
            let _ = writeln!(out);
        }

        for tier in [Tier::T1, Tier::T2, Tier::T3, Tier::T4, Tier::T5] {
            let tier_outcomes: Vec<&ScenarioOutcome> =
                self.outcomes.iter().filter(|o| o.tier == tier).collect();
            if tier_outcomes.is_empty() {
                continue;
            }
            let _ = writeln!(out, "### {}", tier.label());
            let _ = writeln!(out);
            let _ = writeln!(out, "| ID | Status | Duration | Detail |");
            let _ = writeln!(out, "| --- | --- | --- | --- |");
            for o in tier_outcomes {
                let detail = if o.detail.is_empty() {
                    "—".to_string()
                } else {
                    o.detail.replace('|', "\\|").replace('\n', " ")
                };
                let _ = writeln!(
                    out,
                    "| `{}` | {:?} | {} ms | {} |",
                    o.id, o.status, o.duration_ms, detail
                );
            }
            let _ = writeln!(out);
        }

        // §4 cross-ADR integration outcomes (T3 detail)
        let _ = writeln!(out, "## §4 Cross-ADR integration outcomes");
        let _ = writeln!(out);
        let t3 = self.outcomes.iter().filter(|o| o.tier == Tier::T3);
        if t3.clone().count() == 0 {
            let _ = writeln!(out, "No T3 scenarios in this plan.");
        } else {
            for o in t3 {
                let _ = writeln!(
                    out,
                    "- **`{}`** ({:?}, {} ms): {}",
                    o.id,
                    o.status,
                    o.duration_ms,
                    if o.detail.is_empty() {
                        "passed.".to_string()
                    } else {
                        o.detail.clone()
                    }
                );
            }
        }
        let _ = writeln!(out);

        // §5 stress / soak metrics (T4 detail)
        let _ = writeln!(out, "## §5 Stress / soak metrics");
        let _ = writeln!(out);
        let t4: Vec<_> = self
            .outcomes
            .iter()
            .filter(|o| o.tier == Tier::T4)
            .collect();
        if t4.is_empty() {
            let _ = writeln!(out, "No T4 scenarios in this plan run. (T4 stress / soak typically runs separately on a longer cadence.)");
        } else {
            for o in t4 {
                let _ = writeln!(
                    out,
                    "- **`{}`** ({:?}): {}",
                    o.id,
                    o.status,
                    if o.detail.is_empty() {
                        "no notable findings.".to_string()
                    } else {
                        o.detail.clone()
                    }
                );
            }
        }
        let _ = writeln!(out);

        // §6 failure-mode outcomes (T5 detail)
        let _ = writeln!(out, "## §6 Failure-mode outcomes");
        let _ = writeln!(out);
        let t5 = self.outcomes.iter().filter(|o| o.tier == Tier::T5);
        if t5.clone().count() == 0 {
            let _ = writeln!(out, "No T5 scenarios in this plan.");
        } else {
            for o in t5 {
                let _ = writeln!(
                    out,
                    "- **`{}`** ({:?}): {}",
                    o.id,
                    o.status,
                    if o.detail.is_empty() {
                        "framework recovered as expected.".to_string()
                    } else {
                        o.detail.clone()
                    }
                );
            }
        }
        let _ = writeln!(out);

        // §7 no-panic invariant
        let _ = writeln!(out, "## §7 No-panic invariant verification");
        let _ = writeln!(out);
        let panic_seen = self.outcomes.iter().any(|o| {
            o.stderr_excerpt.contains("panic")
                || o.stdout_excerpt.contains("panicked")
        });
        if panic_seen {
            let _ = writeln!(out, "⚠ At least one scenario captured `panic` in output. Review the affected scenarios in §3.");
        } else {
            let _ = writeln!(out, "No `panic` substring observed in any scenario's stdout / stderr.");
        }
        let _ = writeln!(out);

        // §8 findings
        let _ = writeln!(out, "## §8 Findings");
        let _ = writeln!(out);
        let _ = writeln!(out, "_Decider authors anything observed that didn't match expectations, even when not-fail. Each finding: severity, area, recommendation (block? defer? document?)._");
        let _ = writeln!(out);

        // §9 performance baselines
        let _ = writeln!(out, "## §9 Performance baselines");
        let _ = writeln!(out);
        if plan.performance_baselines.is_empty() {
            let _ = writeln!(out, "_Plan declares no performance baselines._");
        } else {
            let _ = writeln!(
                out,
                "| Metric | Target | Measured at scenario | Observed |"
            );
            let _ = writeln!(out, "| --- | --- | --- | --- |");
            for b in &plan.performance_baselines {
                let _ = writeln!(
                    out,
                    "| {} | {} | `{}` | _decider records_ |",
                    b.metric, b.target, b.measured_at
                );
            }
        }
        let _ = writeln!(out);

        // §10 recommendation
        let _ = writeln!(out, "## §10 Recommendation");
        let _ = writeln!(out);
        let _ = writeln!(out, "_Decider's concrete next step: cut final, cut another rc, fix specific issues first._");
        let _ = writeln!(out);

        out
    }
}

fn compute_verdict_hint(outcomes: &[ScenarioOutcome]) -> Verdict {
    // Binary: every scenario executed AND passed → Promote.
    // Any Fail OR any Skip → Block. A Skip is not a pass; it means
    // the test fixture was absent and the framework behaviour was
    // not exercised. Tests tell the truth; a partial truth is not
    // a truth.
    let any_unpassed =
        outcomes.iter().any(|o| o.status != ScenarioStatus::Pass);
    if any_unpassed {
        Verdict::Block
    } else {
        Verdict::Promote
    }
}
