// Copyright (c) 2026 Just a Nerd
// SPDX-License-Identifier: BUSL-1.1

//! Header invariants for generated projection and SDK code.
//!
//! Every generated file (Rust source emitted by the projection
//! crates, TypeScript / Swift / Kotlin / Python / Rust client
//! SDKs, `.proto` files for gRPC, `.graphqls` schema files for
//! GraphQL) carries a header identifying it as generated and
//! refusing hand-edits. A CI pre-commit gate (separate tooling
//! consuming [`carries_generated_header`]) refuses staged
//! modifications to files whose head matches one of the headers
//! below.
//!
//! ## Why
//!
//! Generated code is the materialised projection of the
//! canonical wire schema. A hand-edit to generated code creates
//! a divergence the next regeneration silently overwrites; in
//! the worst case the divergence becomes load-bearing before
//! anyone notices, breaking production on the next benign
//! re-emit. The header is the in-band declaration that prevents
//! the class.

/// Header prepended to every generated Rust source file.
pub const GENERATED_HEADER_RUST: &str =
    "// generated by evo-projection-core; do not edit\n\
     // hand-edits will be overwritten on next regeneration\n";

/// Header prepended to every generated TypeScript source file.
pub const GENERATED_HEADER_TYPESCRIPT: &str =
    "// generated by evo-projection-core; do not edit\n\
     // hand-edits will be overwritten on next regeneration\n";

/// Header prepended to every generated `.proto` file (for the
/// gRPC projection).
pub const GENERATED_HEADER_PROTO: &str =
    "// generated by evo-projection-core; do not edit\n\
     // hand-edits will be overwritten on next regeneration\n";

/// Header prepended to every generated GraphQL schema file.
/// GraphQL uses `#` for comments rather than `//`.
pub const GENERATED_HEADER_GRAPHQL: &str =
    "# generated by evo-projection-core; do not edit\n\
     # hand-edits will be overwritten on next regeneration\n";

/// The substring every header contains; the CI gate uses this
/// for the substring scan so the same check covers every comment
/// dialect (`//` Rust/TS/Proto, `#` GraphQL).
pub const GENERATED_HEADER_MARKER: &str =
    "generated by evo-projection-core; do not edit";

/// Whether the supplied file contents carry one of the
/// generated-code headers.
///
/// The check inspects the first five non-empty lines so a
/// shebang or coding-declaration line before the header (rare
/// but possible in generated scripts) does not bypass the gate.
/// Matching is substring-based against
/// [`GENERATED_HEADER_MARKER`] so the same scan covers every
/// comment dialect.
pub fn carries_generated_header(content: &str) -> bool {
    content
        .lines()
        .filter(|line| !line.trim().is_empty())
        .take(5)
        .any(|line| line.contains(GENERATED_HEADER_MARKER))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn rust_header_starts_with_slash_slash() {
        assert!(GENERATED_HEADER_RUST.starts_with("//"));
        assert!(GENERATED_HEADER_RUST.contains(GENERATED_HEADER_MARKER));
    }

    #[test]
    fn typescript_header_starts_with_slash_slash() {
        assert!(GENERATED_HEADER_TYPESCRIPT.starts_with("//"));
        assert!(GENERATED_HEADER_TYPESCRIPT.contains(GENERATED_HEADER_MARKER));
    }

    #[test]
    fn proto_header_starts_with_slash_slash() {
        assert!(GENERATED_HEADER_PROTO.starts_with("//"));
        assert!(GENERATED_HEADER_PROTO.contains(GENERATED_HEADER_MARKER));
    }

    #[test]
    fn graphql_header_starts_with_hash() {
        assert!(GENERATED_HEADER_GRAPHQL.starts_with("#"));
        assert!(GENERATED_HEADER_GRAPHQL.contains(GENERATED_HEADER_MARKER));
    }

    #[test]
    fn carries_header_detects_rust_file() {
        let content = format!(
            "{}use std::collections::HashMap;\n",
            GENERATED_HEADER_RUST
        );
        assert!(carries_generated_header(&content));
    }

    #[test]
    fn carries_header_detects_typescript_file() {
        let content = format!(
            "{}export interface CapabilityResponse {{}}\n",
            GENERATED_HEADER_TYPESCRIPT
        );
        assert!(carries_generated_header(&content));
    }

    #[test]
    fn carries_header_detects_proto_file() {
        let content =
            format!("{}syntax = \"proto3\";\n", GENERATED_HEADER_PROTO);
        assert!(carries_generated_header(&content));
    }

    #[test]
    fn carries_header_detects_graphql_file() {
        let content =
            format!("{}schema {{ query: Query }}\n", GENERATED_HEADER_GRAPHQL);
        assert!(carries_generated_header(&content));
    }

    #[test]
    fn refuses_hand_written_rust() {
        let content = "// hand-written, not generated\n\
                       use std::collections::HashMap;\n";
        assert!(!carries_generated_header(content));
    }

    #[test]
    fn refuses_empty_content() {
        assert!(!carries_generated_header(""));
        assert!(!carries_generated_header("\n\n\n"));
    }

    #[test]
    fn refuses_header_buried_past_line_five() {
        let content = "\
            // line 1\n\
            // line 2\n\
            // line 3\n\
            // line 4\n\
            // line 5\n\
            // line 6 (this is the line carrying the marker)\n\
            // generated by evo-projection-core; do not edit\n";
        assert!(!carries_generated_header(content));
    }

    #[test]
    fn allows_blank_lines_before_header_within_top_five() {
        let content = format!("\n\n{}", GENERATED_HEADER_RUST);
        assert!(carries_generated_header(&content));
    }
}
