//! The factory trait and its supporting types.

use crate::contract::plugin::Plugin;
use std::time::SystemTime;

/// A plugin that produces variable instances over time.
///
/// Factories extend [`Plugin`] with a retraction policy declaration but
/// otherwise do not add trait methods. Instances are announced and
/// retracted through the
/// [`InstanceAnnouncer`](crate::contract::InstanceAnnouncer) supplied in
/// [`LoadContext`](crate::contract::LoadContext), at whatever cadence the
/// plugin decides.
///
/// Factory kinds:
///
/// - [`RetractionPolicy::Dynamic`]: instances come and go over time. The
///   plugin emits both announcements and retractions. Example: a USB
///   storage factory that emits `announce_instance` when a drive is
///   plugged in and `retract_instance` when it is removed.
///
/// - [`RetractionPolicy::StartupOnly`]: all instances are announced at
///   load time; none are retracted during the plugin's lifetime. Example:
///   a one-shot filesystem enumerator that discovers collections at
///   startup and leaves them announced.
///
/// - [`RetractionPolicy::ShutdownOnly`]: instances are announced over
///   time but retracted only during `unload`. Example: a connection
///   pool that announces each acquired connection as an instance and
///   retracts them all at shutdown.
///
/// The steward uses the declared policy to optimise shutdown ordering and
/// instance cleanup.
pub trait Factory: Plugin {
    /// Declare this factory's retraction policy.
    ///
    /// Called by the steward after `load`. The value is constant for the
    /// life of the plugin instance; plugins that need to change strategy
    /// do so by unloading and reloading.
    fn retraction_policy(&self) -> RetractionPolicy;
}

/// How a factory retracts instances it has announced.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum RetractionPolicy {
    /// Instances come and go at any time. Plugin emits retractions as
    /// the world changes.
    Dynamic,
    /// All instances announced at `load`; no retractions during the
    /// plugin's lifetime. Instances vanish when the plugin unloads.
    StartupOnly,
    /// Instances announced over time; retractions only during `unload`.
    ShutdownOnly,
}

/// An opaque identifier for one factory instance.
///
/// Generated by the factory. The steward treats it as opaque and uses it
/// to address the instance later (e.g. when retracting).
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct InstanceId(pub String);

impl InstanceId {
    /// Construct an instance ID.
    pub fn new(id: impl Into<String>) -> Self {
        Self(id.into())
    }

    /// Borrow the underlying string.
    pub fn as_str(&self) -> &str {
        &self.0
    }
}

impl std::fmt::Display for InstanceId {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(&self.0)
    }
}

impl From<String> for InstanceId {
    fn from(s: String) -> Self {
        Self(s)
    }
}

impl From<&str> for InstanceId {
    fn from(s: &str) -> Self {
        Self(s.to_string())
    }
}

/// An announcement the factory emits when a new instance appears.
#[derive(Debug, Clone)]
pub struct InstanceAnnouncement {
    /// Unique identifier for this instance. The factory uses this same
    /// ID when retracting the instance later.
    pub instance_id: InstanceId,
    /// When the instance was announced.
    pub announced_at: SystemTime,
    /// Opaque payload describing the instance. The steward passes this
    /// through to consumers per the target shelf's shape.
    pub payload: Vec<u8>,
}

impl InstanceAnnouncement {
    /// Construct an announcement with the current time.
    pub fn new(instance_id: impl Into<InstanceId>, payload: Vec<u8>) -> Self {
        Self {
            instance_id: instance_id.into(),
            announced_at: SystemTime::now(),
            payload,
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn instance_id_from_string() {
        let id = InstanceId::from("abc".to_string());
        assert_eq!(id.as_str(), "abc");
    }

    #[test]
    fn instance_id_from_str() {
        let id: InstanceId = "xyz".into();
        assert_eq!(id.as_str(), "xyz");
    }

    #[test]
    fn instance_id_displays_as_inner() {
        let id = InstanceId::new("display-me");
        assert_eq!(format!("{id}"), "display-me");
    }

    #[test]
    fn instance_announcement_new_captures_time() {
        let before = SystemTime::now();
        let a = InstanceAnnouncement::new("i1", vec![1, 2, 3]);
        let after = SystemTime::now();
        assert_eq!(a.instance_id.as_str(), "i1");
        assert_eq!(a.payload, vec![1, 2, 3]);
        assert!(a.announced_at >= before);
        assert!(a.announced_at <= after);
    }

    #[test]
    fn retraction_policy_variants_are_distinct() {
        assert_ne!(RetractionPolicy::Dynamic, RetractionPolicy::StartupOnly);
        assert_ne!(
            RetractionPolicy::StartupOnly,
            RetractionPolicy::ShutdownOnly
        );
        assert_ne!(RetractionPolicy::Dynamic, RetractionPolicy::ShutdownOnly);
    }
}
