//! The warden trait and its supporting types.

use crate::contract::context::CustodyStateReporter;
use crate::contract::error::PluginError;
use crate::contract::plugin::Plugin;
use std::future::Future;
use std::sync::Arc;
use std::time::{Instant, SystemTime};

/// A plugin that takes custody of sustained work.
///
/// Wardens extend [`Plugin`] with the custody verbs from
/// `PLUGIN_CONTRACT.md` section 4: `take_custody`, `course_correct`,
/// `release_custody`. The custody state reporter supplied in
/// [`Assignment::custody_state_reporter`] is how the warden keeps the
/// steward informed while custody is held.
///
/// ## Cancellation
///
/// - Dropping the `take_custody` future before it returns means no
///   custody was acquired. The assignment is considered not taken.
/// - Dropping `course_correct` mid-execution leaves the correction in an
///   undefined state. Wardens should minimise the window where corrections
///   are non-atomic.
/// - Dropping `release_custody` leaves custody in an undefined state.
///   The steward treats the custody as failed and emits a happening.
///
/// ## Concurrent custodies
///
/// A single warden may hold multiple custodies concurrently (e.g. one
/// warden managing multiple simultaneous sessions). Each
/// [`CustodyHandle`] uniquely identifies one custody; operations targeting
/// a specific custody carry the handle.
pub trait Warden: Plugin {
    /// Accept an assignment and begin work.
    ///
    /// The plugin generates a unique [`CustodyHandle`] identifying this
    /// custody and returns it. The steward uses the handle for subsequent
    /// `course_correct` and `release_custody` calls.
    ///
    /// The plugin owns the lifecycle of the work under custody from the
    /// moment this future resolves successfully until `release_custody`
    /// completes or `unload` is called.
    fn take_custody<'a>(
        &'a mut self,
        assignment: Assignment,
    ) -> impl Future<Output = Result<CustodyHandle, PluginError>> + Send + 'a;

    /// Modify work under ongoing custody without revoking it.
    ///
    /// Examples: "seek to position N", "retune to peer X", "reduce
    /// bitrate". Fast-path-eligible; the steward delivers course
    /// corrections through the fast-path channel when available.
    ///
    /// The plugin must complete the correction (or return a timeout error)
    /// within the `course_correction_budget_ms` declared in its manifest.
    fn course_correct<'a>(
        &'a mut self,
        handle: &'a CustodyHandle,
        correction: CourseCorrection,
    ) -> impl Future<Output = Result<(), PluginError>> + Send + 'a;

    /// Gracefully terminate work under custody.
    ///
    /// The plugin winds down the work, reports final state through the
    /// custody state reporter, and returns. After this future resolves
    /// successfully the plugin MUST NOT emit further state for this
    /// handle.
    fn release_custody<'a>(
        &'a mut self,
        handle: CustodyHandle,
    ) -> impl Future<Output = Result<(), PluginError>> + Send + 'a;
}

/// An assignment the steward delivers to a warden.
///
/// Carries the custody type (e.g. `"playback"`), opaque payload, a
/// correlation ID, and the callback through which the warden will report
/// state while the custody is held.
pub struct Assignment {
    /// Custody type identifier, declared by the shelf shape. Tells the
    /// warden what kind of work is being assigned.
    pub custody_type: String,
    /// Opaque payload. The warden deserialises per the shelf's schema.
    pub payload: Vec<u8>,
    /// Correlation ID for logging and tracing.
    pub correlation_id: u64,
    /// Optional deadline for accepting the assignment. If set, the warden
    /// must return from `take_custody` before this time or return a
    /// timeout error.
    pub deadline: Option<Instant>,
    /// Callback through which the warden reports custody state. Supplied
    /// by the steward; the warden clones this Arc as needed for its own
    /// internal plumbing.
    pub custody_state_reporter: Arc<dyn CustodyStateReporter>,
}

impl std::fmt::Debug for Assignment {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("Assignment")
            .field("custody_type", &self.custody_type)
            .field("payload_len", &self.payload.len())
            .field("correlation_id", &self.correlation_id)
            .field("deadline", &self.deadline)
            .field("custody_state_reporter", &"<Arc<dyn CustodyStateReporter>>")
            .finish()
    }
}

/// An opaque identifier for one ongoing custody.
///
/// Generated by the warden in `take_custody`. The steward treats it as
/// opaque and uses it to address subsequent operations on this specific
/// custody.
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct CustodyHandle {
    /// Opaque identifier, warden-generated. Any string the warden can
    /// use to map back to its internal state is valid: a UUID, a
    /// monotonic counter, a subject identifier.
    pub id: String,
    /// When custody was accepted. Aids audit and diagnostic correlation.
    pub started_at: SystemTime,
}

impl CustodyHandle {
    /// Construct a handle with a warden-supplied ID and the current time.
    pub fn new(id: impl Into<String>) -> Self {
        Self {
            id: id.into(),
            started_at: SystemTime::now(),
        }
    }
}

/// A course correction the steward delivers to a warden.
#[derive(Debug, Clone)]
pub struct CourseCorrection {
    /// Correction type identifier, declared by the shelf shape.
    pub correction_type: String,
    /// Opaque payload. The warden deserialises per the shelf's schema.
    pub payload: Vec<u8>,
    /// Correlation ID for logging and tracing.
    pub correlation_id: u64,
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn custody_handle_new_captures_current_time() {
        let before = SystemTime::now();
        let h = CustodyHandle::new("abc-123");
        let after = SystemTime::now();
        assert_eq!(h.id, "abc-123");
        assert!(h.started_at >= before);
        assert!(h.started_at <= after);
    }

    #[test]
    fn custody_handles_with_same_id_are_equal() {
        // Equality is by id alone per Hash/Eq derivation on CustodyHandle.
        // Two handles with the same id but different start times are NOT
        // equal because SystemTime is part of the derivation.
        let h1 = CustodyHandle {
            id: "same".into(),
            started_at: SystemTime::UNIX_EPOCH,
        };
        let h2 = CustodyHandle {
            id: "same".into(),
            started_at: SystemTime::UNIX_EPOCH,
        };
        assert_eq!(h1, h2);

        let h3 = CustodyHandle {
            id: "same".into(),
            started_at: SystemTime::UNIX_EPOCH + std::time::Duration::from_secs(1),
        };
        assert_ne!(h1, h3);
    }

    #[test]
    fn course_correction_debug_useful() {
        let cc = CourseCorrection {
            correction_type: "seek".into(),
            payload: vec![1, 2, 3],
            correlation_id: 99,
        };
        let s = format!("{cc:?}");
        assert!(s.contains("seek"));
        assert!(s.contains("99"));
    }
}
